# Generated by Django 2.1.5 on 2019-01-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category_name',
        ),
    ]
